import React from "react";
import Head from "next/head";
import { getMonth } from "../util";
import CalendarHeader from "../components/CalendarHeader";
import Sidebar from "../components/Sidebar";
import Month from "../components/Month";
import { useContext, useEffect, useState } from "react";
import GlobalContext from "../context/GlobalContext";
import EventModal from "../components/EventModal";
export default function Home() {
  const [currentMonth, setCurrentMonth] = useState(getMonth());
  const { monthIndex, showEventModal } = useContext(GlobalContext);
  useEffect(() => {
    setCurrentMonth(getMonth(monthIndex));
  }, [monthIndex]);

  return (
    <div>
      <Head>
        <title>Calender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <React.Fragment>
        <div className=" h-screen flex flex-col bg-red-500">
          <CalendarHeader />
          <div className="flex-1 flex">
            <Sidebar />
            {showEventModal && <EventModal />}
            <Month month={currentMonth} />
          </div>
        </div>
      </React.Fragment>
    </div>
  );
}
